version: '2'
services:
  elasticsearch:
    container_name: elastic
    image: merch-tools.docker.target.com/merch-tools/elasticsearch-cloud:v5.3.0.1
    restart: unless-stopped
    privileged: true
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xmx1g -Xms1g
      DATA_DIR: /apps/elasticsearch/data
      es_cluster_name: deep_red
      es_discovery_zen_minimum__master__nodes: 1
      es_http_cors_enabled: "true"
      es_http_cors_allow1DASHorigin: '/https?:\/\/localhost(:[0-9]+)?/'

  es-backup:
    container_name: es-backup
    image: es-backup:latest
    restart: unless-stopped
    volumes:
      - /Users/z013tp2/git/harbinger/docker-es-backup:/data/backup
    environment:
      HOST: http://redoak-content-es.stg
      OUTPUT: /data/backup
      CRON_SCHEDULE: "*/1 * * * *"
    extra_hosts:
      - "redoak-content-es.stg:10.65.74.12"
